[app]
name = "mcenter"
key  = "this is your app key"

[app.http]
host = "127.0.0.1"
port = "8050"

[app.grpc]
host = "127.0.0.1"
port = "18050"






[mongodb]
endpoints = ["10.20.2.117:27017"]
username = "mcenter"
password = "123456"
database = "mcenter"

[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"