pkg: go_8_mage/week14_after/micro/tools/demo
name: demo
description: demo样板
enable_keyauth: false
enable_mysql: false
enable_mongodb: true
gen_example: true
http_framework: go-restful
enable_cache: false
