// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: apps/operate/pb/rpc.proto

package operate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RPCClient is the client API for RPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPCClient interface {
	SaveOperateLog(ctx context.Context, in *OperateLog, opts ...grpc.CallOption) (*SaveOperateLogResponse, error)
	QueryOperateLog(ctx context.Context, in *QueryOperateLogRequest, opts ...grpc.CallOption) (*OperateLogSet, error)
}

type rPCClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCClient(cc grpc.ClientConnInterface) RPCClient {
	return &rPCClient{cc}
}

func (c *rPCClient) SaveOperateLog(ctx context.Context, in *OperateLog, opts ...grpc.CallOption) (*SaveOperateLogResponse, error) {
	out := new(SaveOperateLogResponse)
	err := c.cc.Invoke(ctx, "/go8.devcloud.maudit.operate.RPC/SaveOperateLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) QueryOperateLog(ctx context.Context, in *QueryOperateLogRequest, opts ...grpc.CallOption) (*OperateLogSet, error) {
	out := new(OperateLogSet)
	err := c.cc.Invoke(ctx, "/go8.devcloud.maudit.operate.RPC/QueryOperateLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCServer is the server API for RPC service.
// All implementations must embed UnimplementedRPCServer
// for forward compatibility
type RPCServer interface {
	SaveOperateLog(context.Context, *OperateLog) (*SaveOperateLogResponse, error)
	QueryOperateLog(context.Context, *QueryOperateLogRequest) (*OperateLogSet, error)
	mustEmbedUnimplementedRPCServer()
}

// UnimplementedRPCServer must be embedded to have forward compatible implementations.
type UnimplementedRPCServer struct {
}

func (UnimplementedRPCServer) SaveOperateLog(context.Context, *OperateLog) (*SaveOperateLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveOperateLog not implemented")
}
func (UnimplementedRPCServer) QueryOperateLog(context.Context, *QueryOperateLogRequest) (*OperateLogSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryOperateLog not implemented")
}
func (UnimplementedRPCServer) mustEmbedUnimplementedRPCServer() {}

// UnsafeRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCServer will
// result in compilation errors.
type UnsafeRPCServer interface {
	mustEmbedUnimplementedRPCServer()
}

func RegisterRPCServer(s grpc.ServiceRegistrar, srv RPCServer) {
	s.RegisterService(&RPC_ServiceDesc, srv)
}

func _RPC_SaveOperateLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperateLog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).SaveOperateLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go8.devcloud.maudit.operate.RPC/SaveOperateLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).SaveOperateLog(ctx, req.(*OperateLog))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_QueryOperateLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOperateLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).QueryOperateLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go8.devcloud.maudit.operate.RPC/QueryOperateLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).QueryOperateLog(ctx, req.(*QueryOperateLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RPC_ServiceDesc is the grpc.ServiceDesc for RPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go8.devcloud.maudit.operate.RPC",
	HandlerType: (*RPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveOperateLog",
			Handler:    _RPC_SaveOperateLog_Handler,
		},
		{
			MethodName: "QueryOperateLog",
			Handler:    _RPC_QueryOperateLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/operate/pb/rpc.proto",
}
